[tools]
typescript = "latest"
biome = "latest"
python = "3.14"
uv = "latest"


[tasks]
check-js = "tsc --noEmit"
check-py = "uv run pyright"
lint-py = "uv run ruff check"
lint-js = "biome check"
build = "uv build"

[tasks.dev]
run = "uv run layout-tui"
description = "Launch the TUI"
